client:
  batch_size: 128
  fed_algo: FedAvgECGR
  lr: 0.001
  momentum: 0.9
  num_local_epoch: 1
system:
  dataset: MNIST
  dirichlet_alpha: 0.01
  extraction_beta: 0.2
  i_seed: 2025
  model: LeNet
  num_client: 10
  num_round: 100
  res_root: results
